// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void login()
    {
        driver.Navigate().GoToUrl("https://buybook.ba/");
        driver.Manage().Window.Size = new System.Drawing.Size(784, 824);
        driver.FindElement(By.CssSelector(".bi-person-circle")).Click();
        driver.FindElement(By.Id("email_1")).Click();
        driver.FindElement(By.Id("email_1")).SendKeys("ahodzic1@etf.unsa.ba");
        driver.FindElement(By.Id("exampleInputPassword01")).Click();
        driver.FindElement(By.Id("exampleInputPassword01")).SendKeys("malena122");
        driver.FindElement(By.Name("giris")).Click();
    }
}
